-- Supabase seed data for development
-- This file contains test data for local development
-- Run with: supabase db reset (includes seed data)

-- Enable Row Level Security on all tables by default
-- This ensures security-first development

-- Example: Create a simple health check table
-- Use DO block to ensure proper transaction handling
DO $$
BEGIN
    CREATE TABLE IF NOT EXISTS public._health_check (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status TEXT DEFAULT 'ok',
        checked_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- RLS enabled by default
    ALTER TABLE public._health_check ENABLE ROW LEVEL SECURITY;

    -- Drop existing policies if they exist (idempotent)
    DROP POLICY IF EXISTS "Allow anonymous health check reads" ON public._health_check;
    DROP POLICY IF EXISTS "Allow authenticated health check reads" ON public._health_check;

    -- Allow anonymous reads for health checks (adjust as needed)
    CREATE POLICY "Allow anonymous health check reads" ON public._health_check
        FOR SELECT
        TO anon
        USING (true);

    CREATE POLICY "Allow authenticated health check reads" ON public._health_check
        FOR SELECT
        TO authenticated
        USING (true);

    -- Insert initial health check record
    INSERT INTO public._health_check (status)
    SELECT 'healthy'
    WHERE NOT EXISTS (SELECT 1 FROM public._health_check LIMIT 1);
END $$;