# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
early_access: false
reviews:
  profile: chill
  auto_review:
    enabled: true # automatically review all PRs
    labels: [] # empty = review all PRs (use ['ai-review'] to require label)
  high_level_summary: true
  request_changes_workflow: false
  path_filters:
    # Exclude low-risk planning/example docs
    - '!specs/**'
    - '!plans/**'
    - '!tasks/**'
    - '!docs/micro-lessons/**'
    - '!docs/research/**'

    # Include all code (including scripts and tests - they're critical!)
    - 'apps/**'              # Includes E2E tests (*.spec.ts) - critical for production confidence
    - 'packages/**'          # Includes unit tests (*.test.ts) - validates core logic
    - 'scripts/**'           # Database migrations, destructive ops, production scripts

    # Include critical LLM-facing documentation
    - '.claude/**'          # Skills, commands, prompts - LLMs execute these
    - 'docs/llm/**'         # Constitution, guidelines - LLMs follow these
    - 'docs/adr/**'         # Architecture decisions - LLMs implement these
    - 'docs/testing/**'     # Test standards - LLMs apply these
    - 'docs/ai/**'          # AI guidelines - LLMs follow these
    - 'docs/scripts/**'     # Script documentation and safety guidelines
    - 'CONTRIBUTING.md'     # Workflow rules - LLMs follow these
    - 'SECURITY.md'         # Security policy - Critical for all code

    # Include infrastructure and deployment configuration
    - 'vercel.json'         # Vercel deployment config - affects production builds
    - 'docs/DEPLOYMENT.md'  # Deployment procedures - critical for production
    - 'README.md'           # Main documentation - developer entry point
    - '.env.example'        # Environment variable templates - security check
