# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
early_access: false
reviews:
  profile: chill
  auto_review:
    enabled: true # automatically review all PRs
    labels: [] # empty = review all PRs (use ['ai-review'] to require label)
  high_level_summary: true
  request_changes_workflow: false
  path_filters:
    - '!docs/**'
    - '!scripts/**'
    - '!**/*.md'
    - '!**/*.spec.*'
    - '!**/*.test.*'
    - 'apps/**'
    - 'packages/**'
